Check if .env file exists before sourcing it

diff --git a/bin/create-moodle-config b/bin/create-moodle-config
--- a/bin/create-moodle-config
+++ b/bin/create-moodle-config
@@ -1,6 +1,12 @@
 #!/usr/bin/env bash
 
-source .env
+if [ -f .env ]; 
+then
+    source .env
+else
+    echo 'Error: No .env file in current directory.'
+    exit 1
+fi
 
 cp config.docker-template.php $MOODLE_DOCKER_WWWROOT/config.php
 
diff --git a/bin/moodle-docker-compose b/bin/moodle-docker-compose
--- a/bin/moodle-docker-compose
+++ b/bin/moodle-docker-compose
@@ -1,7 +1,13 @@
 #!/usr/bin/env bash
 set -e
 
-source .env
+if [ -f .env ]; 
+then
+    source .env
+else
+    echo 'Error: No .env file in current directory.'
+    exit 1
+fi
 
 if [ ! -d "$MOODLE_DOCKER_WWWROOT" ];
 then
